apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notebook-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
        - name: jupyter
          image: jupyter/base-notebook:latest # Or a more specific recent tag if preferred
          ports:
            - containerPort: 8888
          volumeMounts:
            - name: notebook-storage
              mountPath: /home/jovyan/work
          # --- UPDATED ARGS ---
          args:
            [
              "start-notebook.py",
              "--ServerApp.token=''",
              "--ServerApp.port=8888",
              "--ServerApp.ip='0.0.0.0'",  # Explicitly listen on all interfaces
              "--ServerApp.allow_origin='*'", # Often needed depending on access method
              "--ServerApp.notebook_dir='/home/jovyan/work'" # Explicitly set workdir
            ]
          # --- END UPDATED ARGS ---
      volumes:
        - name: notebook-storage
          persistentVolumeClaim:
            claimName: notebook-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter
spec:
  type: LoadBalancer
  selector:
    app: jupyter
  ports:
    - port: 8888
      targetPort: 8888